-- One-Line production schema — Supabase/Postgres
-- Run this once in the Supabase SQL editor for the client's NEW project.
create extension if not exists pgcrypto;

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  image_url text not null default '',
  subtitle text not null default '',
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.subcategories (
  id uuid primary key default gen_random_uuid(),
  category_id uuid not null references public.categories(id) on delete cascade,
  name text not null,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique(category_id,name)
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  barcode text unique,
  name text not null,
  description text not null default '',
  category_id uuid references public.categories(id) on delete set null,
  subcategory_id uuid references public.subcategories(id) on delete set null,
  price numeric(12,2) not null default 0,
  mrp numeric(12,2) not null default 0,
  product_type text not null default 'Simple' check (product_type in ('Simple','One Option','Colour + Option')),
  option_title text not null default 'Size',
  images text[] not null default '{}',
  stock integer not null default 0 check (stock >= 0),
  active boolean not null default true,
  customer_visible boolean not null default true,
  b2b_only boolean not null default false,
  ask_for_price boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_variants (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  color text not null default '',
  size text not null default '',
  stock integer not null default 0 check (stock >= 0),
  price numeric(12,2) not null default 0,
  barcode text unique,
  image_url text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique(product_id,color,size)
);

create table if not exists public.subitems (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  barcode text unique,
  name text not null,
  price numeric(12,2) not null default 0,
  option_title text not null default 'Size',
  images text[] not null default '{}',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.subitem_variants (
  id uuid primary key default gen_random_uuid(),
  subitem_id uuid not null references public.subitems(id) on delete cascade,
  color text not null default '',
  size text not null default '',
  stock integer not null default 0 check (stock >= 0),
  price numeric(12,2) not null default 0,
  barcode text unique,
  image_url text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique(subitem_id,color,size)
);

create table if not exists public.product_subitems (
  product_id uuid not null references public.products(id) on delete cascade,
  subitem_id uuid not null references public.subitems(id) on delete cascade,
  sort_order integer not null default 0,
  primary key(product_id,subitem_id)
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  name text not null,
  role text not null check (role in ('admin','management','staff','receiver')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  phone text not null unique,
  name text not null default '',
  business_name text not null default '',
  job_title text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create table if not exists public.customer_sessions (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.customers(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.customer_activity (
  id bigint generated by default as identity primary key,
  customer_id uuid references public.customers(id) on delete set null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.customer_carts (
  customer_id uuid primary key references public.customers(id) on delete cascade,
  items jsonb not null default '[]'::jsonb,
  piece_count integer not null default 0 check(piece_count >= 0),
  total numeric(12,2) not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_code text not null unique,
  customer_id uuid references public.customers(id) on delete set null,
  customer_name text not null default '',
  phone text not null default '',
  address text not null default '',
  business text not null default '',
  delivery text not null default '',
  payment text not null default '',
  status text not null default 'Confirmed',
  total numeric(12,2) not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  subitem_id uuid references public.subitems(id) on delete set null,
  item_type text not null default 'product',
  item_name text not null,
  item_code text not null default '',
  color text not null default '',
  size text not null default '',
  qty integer not null check(qty > 0),
  unit_price numeric(12,2) not null default 0,
  design_json jsonb,
  group_key text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.stock_movements (
  id bigint generated by default as identity primary key,
  product_id uuid references public.products(id) on delete set null,
  product_variant_id uuid references public.product_variants(id) on delete set null,
  subitem_id uuid references public.subitems(id) on delete set null,
  subitem_variant_id uuid references public.subitem_variants(id) on delete set null,
  qty_delta integer not null,
  actor_id uuid references auth.users(id) on delete set null,
  reason text not null default '',
  order_id uuid references public.orders(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.store_settings (
  id integer primary key default 1 check(id=1),
  whatsapp text not null default '',
  custom_tshirt_base_price numeric(12,2) not null default 350,
  custom_polo_base_price numeric(12,2) not null default 400,
  custom_standard_extra numeric(12,2) not null default 50,
  custom_premium_extra numeric(12,2) not null default 100,
  custom_qty_tier2_min integer not null default 11,
  custom_qty_tier3_min integer not null default 51,
  custom_qty_tier4_min integer not null default 101,
  custom_qty_11_50_discount numeric(12,2) not null default 30,
  custom_qty_51_100_discount numeric(12,2) not null default 60,
  custom_qty_101_plus_discount numeric(12,2) not null default 100,
  custom_large_print_threshold_pct numeric(6,2) not null default 50,
  custom_dtf_small numeric(12,2) not null default 10,
  custom_dtf_large numeric(12,2) not null default 20,
  custom_screen_small numeric(12,2) not null default 10,
  custom_screen_large numeric(12,2) not null default 20,
  custom_embroidery_small numeric(12,2) not null default 50,
  custom_embroidery_large numeric(12,2) not null default 100,
  custom_sublimation_small numeric(12,2) not null default 10,
  custom_sublimation_large numeric(12,2) not null default 20,
  updated_at timestamptz not null default now()
);
insert into public.store_settings(id) values(1) on conflict(id) do nothing;

create table if not exists public.print_types (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  price numeric(12,2) not null default 0,
  note text not null default '',
  light_only boolean not null default false,
  active boolean not null default true,
  sort_order integer not null default 0
);

create table if not exists public.delivery_methods (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  note text not null default '',
  active boolean not null default true,
  sort_order integer not null default 0
);

insert into public.print_types(name,price,note,light_only,sort_order) values
 ('DTF Print',10,'Vivid colour · works on light and dark garments',false,1),
 ('Screen Print',10,'Durable and efficient for quantity orders',false,2),
 ('Embroidery',50,'Premium stitched thread finish',false,3),
 ('Sublimation',10,'Light colours only',true,4)
on conflict(name) do nothing;

insert into public.delivery_methods(name,note,sort_order) values
 ('Courier','Door delivery · charge confirmed with order',1),
 ('Store pickup','Collect from the production desk',2),
 ('Bus parcel','Collect from your selected bus stand',3)
on conflict(name) do nothing;

create or replace function public.make_item_code() returns text language plpgsql as $$
declare chars text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; out_code text; i int;
begin
  loop
    out_code := '';
    for i in 1..6 loop out_code := out_code || substr(chars, 1 + floor(random()*length(chars))::int, 1); end loop;
    if out_code ~ '[A-Z]' and out_code ~ '[0-9]' and not exists(select 1 from public.products where code=out_code) and not exists(select 1 from public.subitems where code=out_code) then return out_code; end if;
  end loop;
end $$;

create or replace function public.apply_item_code() returns trigger language plpgsql as $$
begin
  if nullif(trim(new.barcode),'') is not null then
    new.code := trim(new.barcode);
  elsif nullif(trim(new.code),'') is null then
    new.code := public.make_item_code();
  else
    new.code := upper(trim(new.code));
    if new.code !~ '^[A-Z0-9]{6}$' or new.code !~ '[A-Z]' or new.code !~ '[0-9]' then
      raise exception 'Manual item code must be exactly 6 alphanumeric characters and contain at least one letter and one number';
    end if;
  end if;
  new.code := upper(trim(new.code));
  if tg_table_name='products' and exists(select 1 from public.subitems s where s.code=new.code) then raise exception 'Item code already exists on a subitem'; end if;
  if tg_table_name='subitems' and exists(select 1 from public.products p where p.code=new.code) then raise exception 'Item code already exists on a product'; end if;
  new.updated_at := now();
  return new;
end $$;
drop trigger if exists trg_products_code on public.products;
create trigger trg_products_code before insert or update on public.products for each row execute function public.apply_item_code();
drop trigger if exists trg_subitems_code on public.subitems;
create trigger trg_subitems_code before insert or update on public.subitems for each row execute function public.apply_item_code();

create or replace function public.has_role(roles text[]) returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles p where p.id=auth.uid() and p.active and p.role=any(roles));
$$;

alter table public.categories enable row level security;
alter table public.subcategories enable row level security;
alter table public.products enable row level security;
alter table public.product_variants enable row level security;
alter table public.subitems enable row level security;
alter table public.subitem_variants enable row level security;
alter table public.product_subitems enable row level security;
alter table public.profiles enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.stock_movements enable row level security;
alter table public.store_settings enable row level security;
alter table public.print_types enable row level security;
alter table public.delivery_methods enable row level security;
alter table public.customers enable row level security;
alter table public.customer_sessions enable row level security;
alter table public.customer_activity enable row level security;
alter table public.customer_carts enable row level security;

-- Public catalogue reads. Empty categories are hidden by the frontend unless they contain a live product.
create policy "public categories read" on public.categories for select using(active);
create policy "public subcategories read" on public.subcategories for select using(active);
create policy "public products read" on public.products for select using(active);
create policy "public product variants read" on public.product_variants for select using(active);
create policy "public subitems read" on public.subitems for select using(active);
create policy "public subitem variants read" on public.subitem_variants for select using(active);
create policy "public product subitems read" on public.product_subitems for select using(true);
create policy "public store settings read" on public.store_settings for select using(true);
create policy "public print types read" on public.print_types for select using(active);
create policy "public delivery methods read" on public.delivery_methods for select using(active);

-- Portal reads.
create policy "staff profiles own or admin" on public.profiles for select using(id=auth.uid() or public.has_role(array['admin']));
create policy "staff orders read" on public.orders for select using(public.has_role(array['admin','receiver']));
create policy "staff order items read" on public.order_items for select using(public.has_role(array['admin','receiver']));
create policy "staff stock movements read" on public.stock_movements for select using(public.has_role(array['admin','staff']));
create policy "activity admin management read" on public.customer_activity for select using(public.has_role(array['admin']));
create policy "customers admin management read" on public.customers for select using(public.has_role(array['admin']));
create policy "customer carts admin management read" on public.customer_carts for select using(public.has_role(array['admin']));

-- Admin / management catalogue writes.
create policy "catalogue products insert" on public.products for insert with check(public.has_role(array['admin','management']));
create policy "catalogue products update" on public.products for update using(public.has_role(array['admin','management'])) with check(public.has_role(array['admin','management']));
create policy "catalogue products delete" on public.products for delete using(public.has_role(array['admin']));
create policy "catalogue variants insert" on public.product_variants for insert with check(public.has_role(array['admin','management']));
create policy "catalogue variants update" on public.product_variants for update using(public.has_role(array['admin','management'])) with check(public.has_role(array['admin','management']));
create policy "catalogue variants delete" on public.product_variants for delete using(public.has_role(array['admin','management']));
create policy "catalogue subitems insert" on public.subitems for insert with check(public.has_role(array['admin','management']));
create policy "catalogue subitems update" on public.subitems for update using(public.has_role(array['admin','management'])) with check(public.has_role(array['admin','management']));
create policy "catalogue subitems delete" on public.subitems for delete using(public.has_role(array['admin']));
create policy "catalogue subvariants insert" on public.subitem_variants for insert with check(public.has_role(array['admin','management']));
create policy "catalogue subvariants update" on public.subitem_variants for update using(public.has_role(array['admin','management'])) with check(public.has_role(array['admin','management']));
create policy "catalogue subvariants delete" on public.subitem_variants for delete using(public.has_role(array['admin','management']));
create policy "product subitems write" on public.product_subitems for all using(public.has_role(array['admin','management'])) with check(public.has_role(array['admin','management']));

-- Admin + Management can add/edit catalogue structure. Destructive structure deletes stay Admin-only.
create policy "categories manage insert" on public.categories for insert with check(public.has_role(array['admin','management']));
create policy "categories manage update" on public.categories for update using(public.has_role(array['admin','management'])) with check(public.has_role(array['admin','management']));
create policy "categories admin delete" on public.categories for delete using(public.has_role(array['admin']));
create policy "subcategories manage insert" on public.subcategories for insert with check(public.has_role(array['admin','management']));
create policy "subcategories manage update" on public.subcategories for update using(public.has_role(array['admin','management'])) with check(public.has_role(array['admin','management']));
create policy "subcategories admin delete" on public.subcategories for delete using(public.has_role(array['admin']));
create policy "settings admin write" on public.store_settings for all using(public.has_role(array['admin'])) with check(public.has_role(array['admin']));
create policy "prints admin write" on public.print_types for all using(public.has_role(array['admin'])) with check(public.has_role(array['admin']));
create policy "delivery admin write" on public.delivery_methods for all using(public.has_role(array['admin'])) with check(public.has_role(array['admin']));

-- Receiver order status updates.
create policy "order status update" on public.orders for update using(public.has_role(array['admin','receiver'])) with check(public.has_role(array['admin','receiver']));

-- Storage bucket for catalogue/team-design artwork.
insert into storage.buckets(id,name,public) values('product-images','product-images',true) on conflict(id) do update set public=true;
create policy "public product images" on storage.objects for select using(bucket_id='product-images');
create policy "portal uploads" on storage.objects for insert with check(bucket_id='product-images' and public.has_role(array['admin','management']));
create policy "portal image updates" on storage.objects for update using(bucket_id='product-images' and public.has_role(array['admin','management'])) with check(bucket_id='product-images' and public.has_role(array['admin','management']));
create policy "portal image deletes" on storage.objects for delete using(bucket_id='product-images' and public.has_role(array['admin','management']));

-- Atomic stock adjustment used by stock desks.
create or replace function public.adjust_stock(p_variant uuid, p_delta integer, p_reason text default 'Manual stock adjustment') returns void
language plpgsql security definer set search_path=public as $$
declare r public.product_variants%rowtype;
begin
  if not public.has_role(array['admin','staff']) then raise exception 'Not authorized'; end if;
  if public.has_role(array['staff']) and p_delta >= 0 then raise exception 'Staff may only mark stock as sold'; end if;
  select * into r from public.product_variants where id=p_variant for update;
  if not found then raise exception 'Variant not found'; end if;
  if r.stock + p_delta < 0 then raise exception 'Stock cannot be negative'; end if;
  update public.product_variants set stock=stock+p_delta where id=p_variant;
  update public.products set stock=(select coalesce(sum(stock),0) from public.product_variants where product_id=r.product_id) where id=r.product_id;
  insert into public.stock_movements(product_id,product_variant_id,qty_delta,actor_id,reason) values(r.product_id,p_variant,p_delta,auth.uid(),p_reason);
end $$;

-- Server-side customizer pricing. The browser sends the design geometry; the database applies the live admin pricing rules.
create or replace function public.custom_design_unit_price(p_design jsonb,p_qty integer)
returns numeric language plpgsql stable security definer set search_path=public as $$
declare
  s public.store_settings%rowtype;
  v_type text := coalesce(p_design->>'garmentType','');
  v_material text := coalesce(p_design->>'materialQuality','Budget');
  v_print text := lower(coalesce(p_design->>'printType','DTF Print'));
  v_base numeric := 0;
  v_extra numeric := 0;
  v_discount numeric := 0;
  v_small numeric := 10;
  v_large numeric := 20;
  v_print_cost numeric := 0;
  v_surface jsonb;
  v_layer jsonb;
  v_width numeric := 0;
  v_threshold numeric := 50;
  v_print_count integer := 0;
begin
  select * into s from public.store_settings where id=1;
  if not found then raise exception 'Store pricing settings are missing'; end if;
  if v_type='T-Shirt' then v_base:=s.custom_tshirt_base_price;
  elsif v_type='Polo' then v_base:=s.custom_polo_base_price;
  else raise exception 'This saved custom garment type is no longer available. Please redesign it as T-Shirt or Polo.';
  end if;

  if lower(v_material)='standard' then v_extra:=s.custom_standard_extra;
  elsif lower(v_material)='premium' then v_extra:=s.custom_premium_extra;
  else v_extra:=0;
  end if;

  if greatest(1,coalesce(p_qty,1))>=s.custom_qty_tier4_min then v_discount:=s.custom_qty_101_plus_discount;
  elsif greatest(1,coalesce(p_qty,1))>=s.custom_qty_tier3_min then v_discount:=s.custom_qty_51_100_discount;
  elsif greatest(1,coalesce(p_qty,1))>=s.custom_qty_tier2_min then v_discount:=s.custom_qty_11_50_discount;
  end if;

  if v_print like '%embroid%' then v_small:=s.custom_embroidery_small;v_large:=s.custom_embroidery_large;
  elsif v_print like '%screen%' then v_small:=s.custom_screen_small;v_large:=s.custom_screen_large;
  elsif v_print like '%sublim%' then v_small:=s.custom_sublimation_small;v_large:=s.custom_sublimation_large;
  else v_small:=s.custom_dtf_small;v_large:=s.custom_dtf_large;
  end if;
  v_threshold:=greatest(1,coalesce(s.custom_large_print_threshold_pct,50));

  for v_surface in select value from jsonb_each(coalesce(p_design->'surfaceDesigns','{}'::jsonb)) loop
    for v_layer in select value from jsonb_array_elements(coalesce(v_surface->'layers','[]'::jsonb)) loop
      v_width:=greatest(0,coalesce(nullif(v_layer->>'pricingWidthPct','')::numeric,nullif(v_layer->>'scale','')::numeric,0));
      v_print_cost:=v_print_cost + case when v_width>v_threshold then v_large else v_small end;
      v_print_count:=v_print_count+1;
    end loop;
  end loop;

  -- Compatibility with a legacy front-only design that predates surfaceDesigns/layers.
  if v_print_count=0 and (coalesce(p_design->>'text','')<>'' or coalesce(p_design->>'uploadedImage','')<>'') then
    v_width:=greatest(coalesce(nullif(p_design->>'textScale','')::numeric,0),coalesce(nullif(p_design->>'imageScale','')::numeric,0));
    v_print_cost:=case when v_width>v_threshold then v_large else v_small end;
  end if;

  return greatest(0,v_base+v_extra+v_print_cost-v_discount);
end $$;

-- Atomic order creation + stock validation/decrement. Called only from the place-order Edge Function using a server secret.
create or replace function public.place_bulk_order(
  p_customer_id uuid,
  p_customer_name text,
  p_phone text,
  p_address text,
  p_business text,
  p_delivery text,
  p_payment text,
  p_items jsonb
) returns jsonb language plpgsql security definer set search_path=public as $$
declare
  v_order_id uuid := gen_random_uuid();
  v_order_code text := 'OL-' || to_char(now(),'YYMMDD') || '-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,6));
  v_item jsonb; v_line jsonb; v_sub jsonb; v_total numeric := 0; v_price numeric; v_qty int; v_stock int; v_variant uuid; v_subvariant uuid; v_name text; v_code text;
begin
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items)=0 then raise exception 'Cart is empty'; end if;
  insert into public.orders(id,order_code,customer_id,customer_name,phone,address,business,delivery,payment,status,total,metadata)
  values(v_order_id,v_order_code,p_customer_id,coalesce(p_customer_name,''),coalesce(p_phone,''),coalesce(p_address,''),coalesce(p_business,''),coalesce(p_delivery,''),coalesce(p_payment,''),'Confirmed',0,'{}');

  for v_item in select * from jsonb_array_elements(p_items) loop
    if coalesce(v_item->>'itemType','product')='custom_design' then
      v_qty := greatest(1,coalesce((v_item->>'qty')::int,1));
      v_price := public.custom_design_unit_price(coalesce(v_item->'design','{}'::jsonb),v_qty);
      insert into public.order_items(order_id,item_type,item_name,item_code,qty,unit_price,design_json,group_key)
      values(v_order_id,'custom_design',coalesce(v_item->>'name','Custom design'),coalesce(v_item->>'code',''),v_qty,v_price,v_item->'design',coalesce(v_item->>'groupKey',''));
      v_total := v_total + v_qty*v_price;
      continue;
    elsif coalesce(v_item->>'itemType','product')='team_design' then
      -- Team-upload designs remain enquiry/quote items.
      v_qty := greatest(1,coalesce((v_item->>'qty')::int,1)); v_price := 0;
      insert into public.order_items(order_id,item_type,item_name,item_code,qty,unit_price,design_json,group_key)
      values(v_order_id,'team_design',coalesce(v_item->>'name','Team design'),coalesce(v_item->>'code',''),v_qty,v_price,v_item->'design',coalesce(v_item->>'groupKey',''));
      continue;
    end if;

    for v_line in select * from jsonb_array_elements(coalesce(v_item->'lines','[]'::jsonb)) loop
      v_qty := greatest(0,coalesce((v_line->>'qty')::int,0)); if v_qty=0 then continue; end if;
      v_variant := nullif(v_line->>'variantId','')::uuid;
      if v_variant is not null then
        select pv.stock,pv.price,p.name,p.code into v_stock,v_price,v_name,v_code
        from public.product_variants pv join public.products p on p.id=pv.product_id
        where pv.id=v_variant and pv.product_id=(v_item->>'productId')::uuid and pv.active and p.active and p.customer_visible and not p.b2b_only
        for update of pv,p;
        if not found or v_stock < v_qty then raise exception 'Stock changed or product is unavailable'; end if;
        update public.product_variants set stock=stock-v_qty where id=v_variant;
        update public.products set stock=(select coalesce(sum(stock),0) from public.product_variants where product_id=(v_item->>'productId')::uuid) where id=(v_item->>'productId')::uuid;
      else
        select p.stock,p.price,p.name,p.code into v_stock,v_price,v_name,v_code
        from public.products p
        where p.id=(v_item->>'productId')::uuid and p.active and p.customer_visible and not p.b2b_only
        for update;
        if not found or v_stock < v_qty then raise exception 'Stock changed or product is unavailable'; end if;
        update public.products set stock=stock-v_qty where id=(v_item->>'productId')::uuid;
      end if;
      -- Never trust catalogue identity or pricing supplied by the browser; use locked database values.
      v_price := greatest(0,coalesce(v_price,0));
      insert into public.order_items(order_id,product_id,item_type,item_name,item_code,color,size,qty,unit_price,design_json,group_key)
      values(v_order_id,(v_item->>'productId')::uuid,'product',v_name,v_code,coalesce(v_line->>'color',''),coalesce(v_line->>'size',''),v_qty,v_price,v_item->'design',coalesce(v_item->>'groupKey',''));
      insert into public.stock_movements(product_id,product_variant_id,qty_delta,reason,order_id) values((v_item->>'productId')::uuid,v_variant,-v_qty,'Customer order',v_order_id);
      v_total := v_total + v_qty*v_price;
    end loop;

    for v_sub in select * from jsonb_array_elements(coalesce(v_item->'subitems','[]'::jsonb)) loop
      if not exists(
        select 1 from public.product_subitems ps
        where ps.product_id=(v_item->>'productId')::uuid and ps.subitem_id=(v_sub->>'subitemId')::uuid
      ) then raise exception 'Subitem is not linked to this product'; end if;
      for v_line in select * from jsonb_array_elements(coalesce(v_sub->'lines','[]'::jsonb)) loop
        v_qty := greatest(0,coalesce((v_line->>'qty')::int,0)); if v_qty=0 then continue; end if;
        v_subvariant := nullif(v_line->>'variantId','')::uuid;
        select sv.stock,sv.price,si.name,si.code into v_stock,v_price,v_name,v_code
        from public.subitem_variants sv join public.subitems si on si.id=sv.subitem_id
        where sv.id=v_subvariant and sv.subitem_id=(v_sub->>'subitemId')::uuid and sv.active and si.active
        for update of sv,si;
        if not found or v_stock < v_qty then raise exception 'Stock changed or subitem is unavailable'; end if;
        update public.subitem_variants set stock=stock-v_qty where id=v_subvariant;
        -- Never trust subitem identity or pricing supplied by the browser; use locked database values.
        v_price := greatest(0,coalesce(v_price,0));
        insert into public.order_items(order_id,subitem_id,item_type,item_name,item_code,color,size,qty,unit_price,group_key)
        values(v_order_id,(v_sub->>'subitemId')::uuid,'subitem',v_name,v_code,coalesce(v_line->>'color',''),coalesce(v_line->>'size',''),v_qty,v_price,coalesce(v_item->>'groupKey',''));
        insert into public.stock_movements(subitem_id,subitem_variant_id,qty_delta,reason,order_id) values((v_sub->>'subitemId')::uuid,v_subvariant,-v_qty,'Customer order',v_order_id);
        v_total := v_total + v_qty*v_price;
      end loop;
    end loop;
  end loop;
  update public.orders set total=v_total where id=v_order_id;
  return jsonb_build_object('id',v_order_id,'orderCode',v_order_code,'total',v_total,'status','Confirmed');
exception when others then
  delete from public.orders where id=v_order_id;
  raise;
end $$;

-- Only the server-side Edge Function may execute the stock-deducting order RPC.
revoke all on function public.place_bulk_order(uuid,text,text,text,text,text,text,jsonb) from public, anon, authenticated;
revoke all on function public.custom_design_unit_price(jsonb,integer) from public, anon, authenticated;
grant execute on function public.custom_design_unit_price(jsonb,integer) to service_role;
grant execute on function public.place_bulk_order(uuid,text,text,text,text,text,text,jsonb) to service_role;

-- Simple-product and subitem stock adjustments for staff stock tracking.
create or replace function public.adjust_product_stock(p_product uuid, p_delta integer, p_reason text default 'Manual stock adjustment') returns void
language plpgsql security definer set search_path=public as $$
declare current_stock integer;
begin
  if not public.has_role(array['admin','staff']) then raise exception 'Not authorized'; end if;
  if public.has_role(array['staff']) and p_delta >= 0 then raise exception 'Staff may only mark stock as sold'; end if;
  select stock into current_stock from public.products where id=p_product for update;
  if not found then raise exception 'Product not found'; end if;
  if current_stock + p_delta < 0 then raise exception 'Stock cannot be negative'; end if;
  update public.products set stock=stock+p_delta where id=p_product;
  insert into public.stock_movements(product_id,qty_delta,actor_id,reason) values(p_product,p_delta,auth.uid(),p_reason);
end $$;

create or replace function public.adjust_subitem_stock(p_variant uuid, p_delta integer, p_reason text default 'Manual subitem stock adjustment') returns void
language plpgsql security definer set search_path=public as $$
declare r public.subitem_variants%rowtype;
begin
  if not public.has_role(array['admin','staff']) then raise exception 'Not authorized'; end if;
  if public.has_role(array['staff']) and p_delta >= 0 then raise exception 'Staff may only mark stock as sold'; end if;
  select * into r from public.subitem_variants where id=p_variant for update;
  if not found then raise exception 'Subitem variant not found'; end if;
  if r.stock + p_delta < 0 then raise exception 'Stock cannot be negative'; end if;
  update public.subitem_variants set stock=stock+p_delta where id=p_variant;
  insert into public.stock_movements(subitem_id,subitem_variant_id,qty_delta,actor_id,reason) values(r.subitem_id,p_variant,p_delta,auth.uid(),p_reason);
end $$;
-- ===== v41 server-authoritative account/cart synchronization =====
-- One-Line v41: server-authoritative customer account sync
-- Run once AFTER the original schema.sql.
-- Safe to run whether or not the v40 migration was already applied.

alter table public.customers
  add column if not exists business_name text not null default '',
  add column if not exists job_title text not null default '',
  add column if not exists updated_at timestamptz not null default now();

create table if not exists public.customer_carts (
  customer_id uuid primary key references public.customers(id) on delete cascade,
  items jsonb not null default '[]'::jsonb,
  piece_count integer not null default 0 check(piece_count >= 0),
  total numeric(12,2) not null default 0,
  updated_at timestamptz not null default now()
);

alter table public.customer_carts enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='public' and tablename='customer_carts'
      and policyname='customer carts admin management read'
  ) then
    create policy "customer carts admin management read"
      on public.customer_carts for select
      using(public.has_role(array['admin']));
  end if;
end $$;

create index if not exists idx_customers_last_seen_at on public.customers(last_seen_at desc);
create index if not exists idx_customer_activity_customer_created on public.customer_activity(customer_id,created_at desc);
create index if not exists idx_orders_customer_created on public.orders(customer_id,created_at desc);

alter table public.customer_carts
  add column if not exists version bigint not null default 0,
  add column if not exists admin_items jsonb not null default '[]'::jsonb;

update public.customer_carts
   set admin_items = items
 where jsonb_array_length(coalesce(admin_items,'[]'::jsonb)) = 0
   and jsonb_array_length(coalesce(items,'[]'::jsonb)) > 0;

create index if not exists idx_customer_carts_updated_at
  on public.customer_carts(updated_at desc);

-- Atomically mutates one customer's cart while holding a row lock.
-- This prevents two phones/laptops from overwriting each other's cart changes.
create or replace function public.customer_cart_mutate(
  p_customer_id uuid,
  p_operation text,
  p_item_key text default null,
  p_item jsonb default null
)
returns table(
  items jsonb,
  piece_count integer,
  total numeric,
  version bigint,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_items jsonb := '[]'::jsonb;
  v_next jsonb := '[]'::jsonb;
  v_found boolean := false;
  v_item jsonb;
  v_line jsonb;
  v_subitem jsonb;
  v_qty integer := 0;
  v_piece_count integer := 0;
  v_total numeric := 0;
  v_admin_items jsonb := '[]'::jsonb;
begin
  if p_customer_id is null then
    raise exception 'Customer is required';
  end if;

  insert into public.customer_carts(customer_id,items,piece_count,total,version,updated_at)
  values(p_customer_id,'[]'::jsonb,0,0,0,now())
  on conflict (customer_id) do nothing;

  select c.items
    into v_items
  from public.customer_carts c
  where c.customer_id = p_customer_id
  for update;

  v_items := coalesce(v_items,'[]'::jsonb);

  if p_operation = 'upsert' then
    if coalesce(trim(p_item_key),'') = '' or p_item is null then
      raise exception 'Cart item key and item are required';
    end if;

    select exists(
      select 1 from jsonb_array_elements(v_items) e(value)
      where e.value->>'key' = p_item_key
    ) into v_found;

    if not v_found and jsonb_array_length(v_items) >= 120 then
      raise exception 'Cart item limit reached';
    end if;

    select coalesce(
      jsonb_agg(
        case when e.value->>'key' = p_item_key then p_item else e.value end
        order by e.ord
      ),
      '[]'::jsonb
    )
    into v_next
    from jsonb_array_elements(v_items) with ordinality as e(value,ord);

    if not v_found then
      v_next := v_next || jsonb_build_array(p_item);
    end if;
    v_items := v_next;

  elsif p_operation = 'remove' then
    if coalesce(trim(p_item_key),'') = '' then
      raise exception 'Cart item key is required';
    end if;
    select coalesce(jsonb_agg(e.value order by e.ord),'[]'::jsonb)
      into v_items
    from jsonb_array_elements(v_items) with ordinality as e(value,ord)
    where e.value->>'key' is distinct from p_item_key;

  elsif p_operation = 'clear' then
    v_items := '[]'::jsonb;
  else
    raise exception 'Invalid cart operation';
  end if;

  -- Recalculate totals from the canonical server cart, never from a cached device value.
  v_piece_count := 0;
  v_total := 0;
  for v_item in select value from jsonb_array_elements(v_items)
  loop
    v_qty := 0;
    if jsonb_typeof(v_item->'bulkLines') = 'array' then
      for v_line in select value from jsonb_array_elements(v_item->'bulkLines')
      loop
        v_qty := v_qty + greatest(0,coalesce(nullif(v_line->>'qty','')::integer,0));
      end loop;
      if jsonb_typeof(v_item->'subitems') = 'array' then
        for v_subitem in select value from jsonb_array_elements(v_item->'subitems')
        loop
          if jsonb_typeof(v_subitem->'lines') = 'array' then
            for v_line in select value from jsonb_array_elements(v_subitem->'lines')
            loop
              v_qty := v_qty + greatest(0,coalesce(nullif(v_line->>'qty','')::integer,0));
            end loop;
          end if;
        end loop;
      end if;
    else
      v_qty := greatest(0,coalesce(nullif(v_item->>'qty','')::integer,0));
    end if;
    v_piece_count := v_piece_count + v_qty;

    if v_item ? 'total' then
      v_total := v_total + greatest(0,coalesce(nullif(v_item->>'total','')::numeric,0));
    else
      v_total := v_total + greatest(0,coalesce(nullif(v_item->>'price','')::numeric,0) * greatest(0,coalesce(nullif(v_item->>'qty','')::numeric,0)));
    end if;
  end loop;

  select coalesce(jsonb_agg(jsonb_strip_nulls(jsonb_build_object(
    'key',v.value->>'key',
    'productId',v.value->>'productId',
    'itemType',coalesce(v.value->>'itemType','product'),
    'name',v.value->>'name',
    'code',v.value->>'code',
    'qty',v.value->'qty',
    'detail',v.value->>'detail',
    'color',v.value->>'color',
    'size',v.value->>'size',
    'total',v.value->'total',
    'price',v.value->'price',
    'bulkLines',v.value->'bulkLines',
    'subitems',v.value->'subitems',
    'sizeQuantities',v.value->'sizeQuantities'
  )) order by v.ord),'[]'::jsonb)
    into v_admin_items
  from jsonb_array_elements(v_items) with ordinality as v(value,ord);

  update public.customer_carts c
     set items = v_items,
         admin_items = v_admin_items,
         piece_count = v_piece_count,
         total = v_total,
         version = c.version + 1,
         updated_at = now()
   where c.customer_id = p_customer_id
  returning c.items,c.piece_count,c.total,c.version,c.updated_at
       into items,piece_count,total,version,updated_at;

  return next;
end;
$$;

revoke all on function public.customer_cart_mutate(uuid,text,text,jsonb) from public;
revoke all on function public.customer_cart_mutate(uuid,text,text,jsonb) from anon;
revoke all on function public.customer_cart_mutate(uuid,text,text,jsonb) from authenticated;
grant execute on function public.customer_cart_mutate(uuid,text,text,jsonb) to service_role;


-- ===== v46 Customize Catalogue =====
-- One-Line v46 — Customize Catalogue + management permissions
-- Included for fresh project installs.

create table if not exists public.custom_catalog_categories (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  description text not null default '',
  image_url text not null default '',
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.custom_catalog_items (
  id uuid primary key default gen_random_uuid(),
  category_id uuid not null references public.custom_catalog_categories(id) on delete cascade,
  title text not null,
  description text not null default '',
  rate numeric(12,2),
  images text[] not null default '{}',
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.custom_catalog_items add column if not exists rate numeric(12,2);

create index if not exists idx_custom_catalog_categories_sort on public.custom_catalog_categories(active,sort_order,name);
create index if not exists idx_custom_catalog_items_category_sort on public.custom_catalog_items(category_id,active,sort_order,created_at);

alter table public.custom_catalog_categories enable row level security;
alter table public.custom_catalog_items enable row level security;

drop policy if exists "public custom catalogue categories read" on public.custom_catalog_categories;
create policy "public custom catalogue categories read" on public.custom_catalog_categories
for select using(active or public.has_role(array['admin','management']));

drop policy if exists "public custom catalogue items read" on public.custom_catalog_items;
create policy "public custom catalogue items read" on public.custom_catalog_items
for select using(
  public.has_role(array['admin','management'])
  or (active and exists(select 1 from public.custom_catalog_categories c where c.id=category_id and c.active))
);

drop policy if exists "custom catalogue categories admin insert" on public.custom_catalog_categories;
create policy "custom catalogue categories admin insert" on public.custom_catalog_categories for insert
with check(public.has_role(array['admin','management']));
drop policy if exists "custom catalogue categories admin update" on public.custom_catalog_categories;
create policy "custom catalogue categories admin update" on public.custom_catalog_categories for update
using(public.has_role(array['admin','management'])) with check(public.has_role(array['admin','management']));
drop policy if exists "custom catalogue categories admin delete" on public.custom_catalog_categories;
create policy "custom catalogue categories admin delete" on public.custom_catalog_categories for delete
using(public.has_role(array['admin']));

drop policy if exists "custom catalogue items admin insert" on public.custom_catalog_items;
create policy "custom catalogue items admin insert" on public.custom_catalog_items for insert
with check(public.has_role(array['admin','management']));
drop policy if exists "custom catalogue items admin update" on public.custom_catalog_items;
create policy "custom catalogue items admin update" on public.custom_catalog_items for update
using(public.has_role(array['admin','management'])) with check(public.has_role(array['admin','management']));
drop policy if exists "custom catalogue items admin delete" on public.custom_catalog_items;
create policy "custom catalogue items admin delete" on public.custom_catalog_items for delete
using(public.has_role(array['admin']));

-- Enquiries are stored as verified customer_activity events with event_type
-- custom_catalog_enquiry. The existing customer-event Edge Function validates
-- the customer's OTP session token before writing them, so no anonymous insert
-- policy is added here.

