(function(){
  "use strict";
  const S=window.OneLineStore,B=window.OneLineBackend,root=document.getElementById('admin-app');
  const requested=(document.body.dataset.portalRole||'admin').toLowerCase();
  const esc=S.esc,money=S.money;
  const state={profile:null,view:requested==='receiver'?'orders':requested==='staff'?'stock':'dashboard',loading:true,error:'',toast:'',menu:false,products:[],categories:[],subcategories:[],subitems:[],orders:[],orderItems:[],activity:[],customers:[],carts:[],profiles:[],editor:null,editSections:{},subEditor:null,categoryEditor:null,query:'',orderQuery:'',orderFilter:'All',customerQuery:''};
  const sb=()=>B?.supa?.();
  const img=(src,alt='')=>'<img src="'+esc(src||'assets/product-placeholder.svg')+'" alt="'+esc(alt)+'" onerror="this.onerror=null;this.src=\'assets/product-placeholder.svg\'">';
  const roles=['admin','management','staff','receiver'];
  const labels={admin:'Admin',management:'Management',staff:'Staff',receiver:'Order Receiving'};
  function notify(msg){state.toast=msg;render();clearTimeout(notify.t);notify.t=setTimeout(()=>{state.toast='';renderToast();},2400);}
  function renderToast(){const el=document.getElementById('adminToast');if(el){el.textContent=state.toast;el.classList.toggle('show',!!state.toast);}}
  function allowed(v){
    const r=requested;
    if(r==='receiver')return ['orders'].includes(v);
    if(r==='staff')return ['dashboard','stock','orders'].includes(v);
    if(r==='management')return ['dashboard','products','subitems','stock','orders','customers','carts','activity'].includes(v);
    return ['dashboard','products','categories','subitems','stock','orders','customers','carts','activity','accounts'].includes(v);
  }
  function canEditCatalog(){return requested==='admin'||requested==='management';}
  function canOrderStatus(){return requested==='admin'||requested==='management'||requested==='receiver';}
  function canManageStructure(){return requested==='admin';}
  function nav(v,label){return allowed(v)?'<button data-view="'+v+'" class="'+(state.view===v?'active':'')+'">'+label+'</button>':'';}
  function roleOkay(){return state.profile&&(state.profile.role===requested||state.profile.role==='admin');}
  function setupScreen(){return '<main class="portal-gate"><section class="portal-gate-card setup"><img src="one-line-logo.webp" alt="One-Line"><span class="portal-kicker">PRODUCTION SETUP</span><h1>Connect the client Supabase project</h1><p>This build intentionally contains no demo catalogue or secret credentials.</p><div class="setup-list"><b>1. Run <code>supabase/schema.sql</code> in the client Supabase SQL editor.</b><b>2. Supabase URL, publishable key and MSG91 Widget client values are already configured in <code>js/config.js</code>.</b><b>3. Deploy the Edge Functions in <code>supabase/functions</code>.</b><b>4. Add the account-level MSG91_AUTH_KEY as an Edge Function secret.</b><b>5. Create the first admin Auth user and matching profile row using <code>supabase/SETUP.md</code>.</b></div><a class="primary-btn" href="index.html">Open customer site</a></section></main>';}
  function loginScreen(){return '<main class="portal-gate"><section class="portal-gate-card"><img src="one-line-logo.webp" alt="One-Line"><span class="portal-kicker">'+esc(labels[requested]||'Portal').toUpperCase()+'</span><h1>Portal login</h1><p>Use the username and password created by an administrator.</p><form id="portalLogin"><label>Username<input name="username" autocomplete="username" required></label><label>Password<input type="password" name="password" autocomplete="current-password" required></label>'+(state.error?'<p class="portal-error">'+esc(state.error)+'</p>':'')+'<button class="primary-btn" type="submit">Sign in</button></form><a class="portal-back" href="index.html">← Back to store</a></section></main>';}
  function wrongPortal(){return '<main class="portal-gate"><section class="portal-gate-card"><span class="portal-kicker">ACCOUNT ROLE</span><h1>This is a '+esc(labels[state.profile.role]||state.profile.role)+' account</h1><p>Open the matching portal, or sign out and use another account.</p><div class="portal-role-links"><a href="admin.html">Admin</a><a href="management.html">Management</a><a href="staff.html">Staff</a><a href="receiver.html">Order receiving</a></div><button class="secondary-btn" data-action="logout">Sign out</button></section></main>';}
  function shell(){
    if(!allowed(state.view))state.view=requested==='receiver'?'orders':'dashboard';
    const low=stockRows().filter(x=>x.stock<=5).length;
    return '<div class="admin-shell portal-'+requested+'"><header class="admin-head"><a class="admin-logo" href="index.html">'+img('one-line-logo.webp','One-Line')+'<span><b>ONE-LINE</b><small>'+esc(labels[requested])+'</small></span></a><button class="menu-toggle" data-action="menu">☰</button><nav class="admin-menu '+(state.menu?'open':'')+'">'+nav('dashboard','Overview')+nav('products','Products')+nav('categories','Categories')+nav('subitems','Subitems')+nav('stock','Stock')+nav('orders','Orders')+nav('customers','Customers')+nav('carts','Live carts')+nav('activity','Activity')+nav('accounts','Accounts')+'<button data-action="refresh-data">Refresh data</button><button data-action="open-store">Open store</button><button data-action="logout">Sign out</button></nav></header><div class="status-card"><span>'+esc(state.profile.name)+' · @'+esc(state.profile.username)+' · '+state.products.length+' products · '+low+' low-stock options</span><div class="portal-switcher"><a href="admin.html">Admin</a><a href="management.html">Management</a><a href="staff.html">Staff</a><a href="receiver.html">Order receiving</a></div></div><main class="admin-main">'+view()+'</main><div class="portal-credit">Developed by <a href="https://quartzsolution.netlify.app/" target="_blank" rel="noopener noreferrer">Quartz Web Solutions</a></div><div class="toast" id="adminToast"></div></div>';
  }
  function view(){return({dashboard:dashboardView,products:productsView,categories:categoriesView,subitems:subitemsView,stock:stockView,orders:ordersView,customers:customersView,carts:cartsView,activity:activityView,accounts:accountsView})[state.view]?.()||dashboardView();}
  function dashboardView(){
    const today=new Date().toDateString(),todayOrders=state.orders.filter(o=>new Date(o.created_at).toDateString()===today),low=stockRows().filter(x=>x.stock<=5),activeCarts=state.carts.filter(c=>Number(c.piece_count||0)>0),recentCustomers=state.customers.filter(c=>Date.now()-new Date(c.last_seen_at||c.created_at).getTime()<86400000).length;
    return '<section class="portal-overview"><div class="panel-head"><div><p class="tag">LIVE OVERVIEW</p><h1>'+esc(labels[requested])+'</h1><p>Catalogue, customers, live carts, stock and orders in one place.</p></div><button class="ghost-btn" data-action="refresh-data">Refresh</button></div><div class="metric-grid admin-metric-grid"><article><span>Products</span><b>'+state.products.length+'</b><small>Catalogue items</small></article><article><span>Orders today</span><b>'+todayOrders.length+'</b><small>'+money(todayOrders.reduce((n,o)=>n+Number(o.total||0),0))+'</small></article><article><span>Customers</span><b>'+state.customers.length+'</b><small>'+recentCustomers+' active in 24h</small></article><article><span>Live carts</span><b>'+activeCarts.length+'</b><small>'+activeCarts.reduce((n,c)=>n+Number(c.piece_count||0),0)+' pieces selected</small></article><article><span>Low stock</span><b>'+low.length+'</b><small>Options with 5 or fewer</small></article></div><div class="admin-quick-actions">'+(canEditCatalog()?'<button data-action="new-product">+ Add product</button>':'')+'<button data-view="orders">Track orders</button>'+((requested==='admin'||requested==='management')?'<button data-view="carts">View live carts</button><button data-view="customers">Customers</button>':'')+'</div>'+(low.length?'<div class="clean-card"><div class="panel-head"><div><p class="tag">ATTENTION</p><h2>Low stock</h2></div><button data-view="stock">Open stock desk</button></div><div class="compact-table">'+low.slice(0,8).map(r=>'<div><b>'+esc(r.name)+'</b><span>'+esc(r.option)+'</span><strong>'+r.stock+'</strong></div>').join('')+'</div></div>':'')+'</section>';
  }
  function productSearchList(){const q=state.query.trim().toLowerCase();return state.products.filter(p=>!q||[p.name,p.code,p.barcode,p.category,p.subcategory].join(' ').toLowerCase().includes(q));}
  function productsView(){
    if(state.editor)return productEditorView();const list=productSearchList();
    return '<section class="clean-card"><div class="panel-head"><div><p class="tag">CATALOGUE</p><h1>Products</h1><p>Search by item name, six-character code or barcode.</p></div>'+(canEditCatalog()?'<button class="submit-small" data-action="new-product">+ Add product</button>':'')+'</div><div class="list-controls"><input id="productSearch" type="search" value="'+esc(state.query)+'" placeholder="Search name, code, barcode, category"><span>'+list.length+' result'+(list.length===1?'':'s')+'</span></div><div class="admin-product-list">'+(list.length?list.map(p=>'<article class="admin-product">'+img(p.image||p.images?.[0],p.name)+'<div class="admin-product-copy"><span class="audience-pill '+(p.audience==='b2b'?'b2b':'')+'">'+(p.audience==='b2b'?'B2B':'Customer')+'</span><b>'+esc(p.name||'Unnamed item')+'</b><small>'+esc(p.category||'')+(p.subcategory?' · '+esc(p.subcategory):'')+'</small></div><div class="admin-product-meta"><b>'+esc(p.code||'------')+'</b><small>'+esc(p.barcode||'No barcode')+'</small></div><div class="admin-product-price"><b>'+money(p.price||0)+'</b><small>'+Number(p.stock||0)+' stock</small></div><div class="row-actions">'+(canEditCatalog()?'<button data-action="edit-product" data-id="'+esc(p.id)+'">Edit</button><button class="danger-link" data-action="delete-product" data-id="'+esc(p.id)+'">Delete</button>':'<span>View only</span>')+'</div></article>').join(''):'<div class="empty-admin">No products yet. Add the first real product; no demo item will be shown to customers.</div>')+'</div></section>';
  }
  function blankProduct(){return{id:'',name:'',description:'',code:'',barcode:'',categoryId:state.categories[0]?.id||'',subcategoryId:'',audience:'retail',price:0,mrp:0,type:'Colour + Option',optionTitle:'Size',stock:0,images:[],variants:[{color:'',size:'',stock:0,price:0,barcode:'',image:'',active:true}],subItemIds:[],active:true};}
  function beginProduct(p){state.editor=p?{...structured(p),subItemIds:(p.subItems||[]).map(x=>x.id)}:blankProduct();state.editSections={basic:!p,media:!p,pricing:!p,variants:!p,subitems:!p};state.view='products';render();}
  function structured(v){return typeof structuredClone==='function'?structuredClone(v):JSON.parse(JSON.stringify(v));}
  function sectionBox(key,title,desc,body){const editable=!!state.editSections[key],existing=!!state.editor.id;return '<section class="portal-edit-section '+(editable?'editing':'')+'"><header><div><b>'+title+'</b><small>'+desc+'</small></div>'+(existing?'<button type="button" data-edit-section="'+key+'">'+(editable?'Done':'Edit')+'</button>':'')+'</header><fieldset '+(editable?'':'disabled')+'>'+body+'</fieldset></section>';}
  function productEditorView(){
    const p=state.editor,subs=state.subcategories.filter(s=>!p.categoryId||s.category_id===p.categoryId),variants=p.variants||[],selected=new Set(p.subItemIds||[]);
    const basic='<div class="editor-grid"><label>Product name<input data-p="name" value="'+esc(p.name||'')+'" required></label><label>Item code<input data-p="code" value="'+esc(p.code||'')+'" maxlength="40" placeholder="Blank = random 6-character code"></label><label>Barcode<input data-p="barcode" value="'+esc(p.barcode||'')+'" placeholder="If entered, barcode becomes item code"></label><label>Visible to<select data-p="audience"><option value="retail" '+(p.audience!=='b2b'?'selected':'')+'>Customer catalogue</option><option value="b2b" '+(p.audience==='b2b'?'selected':'')+'>B2B only</option></select></label><label>Category<select data-p="categoryId"><option value="">Select category</option>'+state.categories.map(c=>'<option value="'+c.id+'" '+(p.categoryId===c.id?'selected':'')+'>'+esc(c.name)+'</option>').join('')+'</select></label><label>Subcategory<select data-p="subcategoryId"><option value="">No subcategory</option>'+subs.map(s=>'<option value="'+s.id+'" '+(p.subcategoryId===s.id?'selected':'')+'>'+esc(s.name)+'</option>').join('')+'</select></label><label class="span2">Description<textarea data-p="description" rows="4">'+esc(p.description||'')+'</textarea></label></div>';
    const media='<div class="upload-zone"><input id="productImages" type="file" accept="image/*" multiple><div><b>Upload product images</b><small>Saved to Supabase Storage.</small></div></div><div class="image-preview-grid">'+(p.images||[]).map((src,i)=>'<div class="image-chip">'+img(src,p.name)+'<button type="button" data-remove-product-image="'+i+'">×</button></div>').join('')+'</div>';
    const pricing='<div class="editor-grid"><label>Base price<input data-p="price" type="number" min="0" step="0.01" value="'+Number(p.price||0)+'"></label><label>MRP<input data-p="mrp" type="number" min="0" step="0.01" value="'+Number(p.mrp||0)+'"></label><label>Simple stock<input data-p="stock" type="number" min="0" value="'+Number(p.stock||0)+'"><small>Used only when Product type is Simple.</small></label><label>Product type<select data-p="type"><option '+(p.type==='Simple'?'selected':'')+'>Simple</option><option '+(p.type==='One Option'?'selected':'')+'>One Option</option><option '+(p.type==='Colour + Option'?'selected':'')+'>Colour + Option</option></select></label><label>Option title<input data-p="optionTitle" value="'+esc(p.optionTitle||'Size')+'" placeholder="Size"></label></div>';
    const variant='<div class="variant-editor-head"><span>Colour / size / stock / price / barcode</span><button type="button" data-action="add-variant">+ Add option</button></div><div class="variant-admin-list">'+variants.map((v,i)=>'<div class="variant-admin-row"><input data-v="color" data-i="'+i+'" value="'+esc(v.color||'')+'" placeholder="Colour"><input data-v="size" data-i="'+i+'" value="'+esc(v.size||'')+'" placeholder="Size"><input data-v="stock" data-i="'+i+'" type="number" min="0" value="'+Number(v.stock||0)+'" placeholder="Stock"><input data-v="price" data-i="'+i+'" type="number" min="0" step="0.01" value="'+Number(v.price??p.price??0)+'" placeholder="Price"><input data-v="barcode" data-i="'+i+'" value="'+esc(v.barcode||'')+'" placeholder="Variant barcode"><input data-v="image" data-i="'+i+'" value="'+esc(v.image||'')+'" placeholder="Image URL optional"><button type="button" data-remove-variant="'+i+'">×</button></div>').join('')+'</div>';
    const subitems='<div class="subitem-link-head"><span>Select any reusable subitems for this product.</span><button type="button" data-action="open-subitems">Create / manage subitems</button></div><div class="subitem-check-grid">'+(state.subitems.length?state.subitems.map(si=>'<label><input type="checkbox" data-sub-link="'+si.id+'" '+(selected.has(si.id)?'checked':'')+'><span><b>'+esc(si.name)+'</b><small>'+esc(si.code||'')+' · '+(si.variants||[]).length+' options</small></span></label>').join(''):'<p>No subitems yet. Create shorts, pants or other add-ons first.</p>')+'</div>';
    return '<section class="clean-card editor-page"><div class="panel-head"><div><p class="tag">'+(p.id?'EDIT PRODUCT':'NEW PRODUCT')+'</p><h1>'+esc(p.name||'Add product')+'</h1><p>Existing products use section-level Edit → Done controls so accidental changes are avoided.</p></div><button class="ghost-btn" data-action="cancel-product">Back to products</button></div><form id="productEditor">'+sectionBox('basic','Basic details','Name, searchable code, barcode and category.',basic)+sectionBox('media','Product images','Upload real catalogue images.',media)+sectionBox('pricing','Pricing & type','Base price and option model.',pricing)+sectionBox('variants','Size / colour stock','Add unlimited option rows and stock.',variant)+sectionBox('subitems','Linked subitems','Attach any number of reusable add-on items.',subitems)+'<div class="editor-savebar"><button type="button" class="ghost-btn" data-action="cancel-product">Cancel</button><button class="primary-btn" type="submit">Save product</button></div></form></section>';
  }
  function categoriesView(){
    const edit=state.categoryEditor,cat=edit?state.categories.find(c=>c.id===edit):null;
    return '<section class="clean-card"><div class="panel-head"><div><p class="tag">STORE STRUCTURE</p><h1>Categories & subcategories</h1><p>Empty categories are automatically hidden from the customer site.</p></div></div><form id="categoryForm" class="inline-create"><input name="name" value="'+esc(cat?.name||'')+'" placeholder="Category name" required><input name="subtitle" value="'+esc(cat?.subtitle||'')+'" placeholder="Short subtitle"><input name="image" type="file" accept="image/*"><button class="primary-btn" type="submit">'+(cat?'Save category':'Add category')+'</button>'+(cat?'<button type="button" class="ghost-btn" data-action="cancel-category-edit">Cancel</button>':'')+'</form><div class="category-admin-grid">'+state.categories.map(c=>'<article><div class="category-admin-photo">'+img(c.image_url,c.name)+'</div><div><b>'+esc(c.name)+'</b><small>'+esc(c.subtitle||'')+'</small></div><div class="row-actions"><button data-action="edit-category" data-id="'+c.id+'">Edit</button><button data-action="delete-category" data-id="'+c.id+'">Delete</button></div><div class="subcategory-box"><b>Subcategories</b>'+state.subcategories.filter(s=>s.category_id===c.id).map(sc=>'<span>'+esc(sc.name)+'<button data-action="delete-subcategory" data-id="'+sc.id+'">×</button></span>').join('')+'<form data-subcategory-form="'+c.id+'"><input name="name" placeholder="Add subcategory" required><button>+</button></form></div></article>').join('')+'</div></section>';
  }
  function blankSub(){return{id:'',name:'',code:'',barcode:'',price:0,optionTitle:'Size',images:[],variants:[{color:'',size:'',stock:0,price:0,barcode:'',image:'',active:true}],active:true};}
  function subitemsView(){
    if(state.subEditor){const si=state.subEditor;return '<section class="clean-card editor-page"><div class="panel-head"><div><p class="tag">REUSABLE SUBITEM</p><h1>'+esc(si.name||'Add subitem')+'</h1><p>Create shorts, pants or any add-on once, then select it on unlimited products.</p></div><button data-action="close-sub-editor">Back</button></div><form id="subitemEditor"><div class="portal-edit-section editing"><fieldset><div class="editor-grid"><label>Name<input data-si="name" value="'+esc(si.name||'')+'" required></label><label>Code<input data-si="code" value="'+esc(si.code||'')+'" placeholder="Blank = random code"></label><label>Barcode<input data-si="barcode" value="'+esc(si.barcode||'')+'"></label><label>Base price<input data-si="price" type="number" min="0" step="0.01" value="'+Number(si.price||0)+'"></label><label>Option title<input data-si="optionTitle" value="'+esc(si.optionTitle||'Size')+'"></label></div><div class="upload-zone"><input id="subImages" type="file" accept="image/*" multiple><div><b>Subitem images</b><small>Optional.</small></div></div><div class="image-preview-grid">'+(si.images||[]).map((src,i)=>'<div class="image-chip">'+img(src,si.name)+'<button type="button" data-remove-sub-image="'+i+'">×</button></div>').join('')+'</div><div class="variant-editor-head"><span>Variants</span><button type="button" data-action="add-sub-variant">+ Add option</button></div><div class="variant-admin-list">'+(si.variants||[]).map((v,i)=>'<div class="variant-admin-row"><input data-sv="color" data-i="'+i+'" value="'+esc(v.color||'')+'" placeholder="Colour"><input data-sv="size" data-i="'+i+'" value="'+esc(v.size||'')+'" placeholder="Size"><input data-sv="stock" data-i="'+i+'" type="number" min="0" value="'+Number(v.stock||0)+'" placeholder="Stock"><input data-sv="price" data-i="'+i+'" type="number" min="0" step="0.01" value="'+Number(v.price??si.price??0)+'" placeholder="Price"><input data-sv="barcode" data-i="'+i+'" value="'+esc(v.barcode||'')+'" placeholder="Barcode"><input data-sv="image" data-i="'+i+'" value="'+esc(v.image||'')+'" placeholder="Image URL"><button type="button" data-remove-sub-variant="'+i+'">×</button></div>').join('')+'</div></fieldset></div><div class="editor-savebar"><button class="primary-btn">Save subitem</button></div></form></section>';}
    return '<section class="clean-card"><div class="panel-head"><div><p class="tag">REUSABLE ADD-ONS</p><h1>Subitems</h1><p>Any product can select one or many of these.</p></div><button class="submit-small" data-action="new-subitem">+ Create subitem</button></div><div class="admin-product-list">'+(state.subitems.length?state.subitems.map(si=>'<article class="admin-product">'+img(si.images?.[0],si.name)+'<div class="admin-product-copy"><b>'+esc(si.name)+'</b><small>'+esc(si.code||'')+(si.barcode?' · '+esc(si.barcode):'')+'</small></div><div class="admin-product-meta"><b>'+(si.variants||[]).length+' options</b><small>'+((si.variants||[]).reduce((n,v)=>n+Number(v.stock||0),0))+' stock</small></div><div class="row-actions"><button data-action="edit-subitem" data-id="'+si.id+'">Edit</button></div></article>').join(''):'<div class="empty-admin">No subitems yet.</div>')+'</div></section>';
  }
  function stockRows(){const rows=[];state.products.forEach(p=>{if(p.variants?.length)p.variants.forEach(v=>rows.push({kind:'product-variant',id:v.id,name:p.name,code:p.code,option:[v.color,v.size].filter(Boolean).join(' · ')||'Option',stock:Number(v.stock||0)}));else rows.push({kind:'product',id:p.id,name:p.name,code:p.code,option:'Simple product',stock:Number(p.stock||0)});});state.subitems.forEach(si=>(si.variants||[]).forEach(v=>rows.push({kind:'subitem',id:v.id,name:si.name,code:si.code,option:[v.color,v.size].filter(Boolean).join(' · ')||'Subitem option',stock:Number(v.stock||0)})));return rows;}
  function stockView(){const q=state.query.trim().toLowerCase(),rows=stockRows().filter(r=>!q||[r.name,r.code,r.option].join(' ').toLowerCase().includes(q));return '<section class="clean-card"><div class="panel-head"><div><p class="tag">LIVE INVENTORY</p><h1>Stock desk</h1><p>Adjustments are written to stock movement history.</p></div></div><div class="list-controls"><input id="stockSearch" type="search" value="'+esc(state.query)+'" placeholder="Search item code, name or size"></div><div class="stock-table"><div class="stock-row head"><span>Item</span><span>Option</span><span>Stock</span><span>Adjust</span></div>'+rows.map(r=>'<div class="stock-row"><span><b>'+esc(r.name)+'</b><small>'+esc(r.code||'')+'</small></span><span>'+esc(r.option)+'</span><strong class="'+(r.stock<=5?'low':'')+'">'+r.stock+'</strong><span class="stock-adjust"><input type="number" min="1" value="1" data-stock-amount="'+r.id+'"><button data-stock-change="'+r.id+'" data-kind="'+r.kind+'" data-sign="1">+</button><button data-stock-change="'+r.id+'" data-kind="'+r.kind+'" data-sign="-1">−</button></span></div>').join('')+'</div></section>';}
  function orderLines(id){return state.orderItems.filter(i=>i.order_id===id);}
  function ordersView(){const q=state.orderQuery.trim().toLowerCase(),list=state.orders.filter(o=>(state.orderFilter==='All'||o.status===state.orderFilter)&&(!q||[o.order_code,o.customer_name,o.phone,o.business].join(' ').toLowerCase().includes(q)));const statuses=['Confirmed','Processing','Ready','Dispatched','Completed','Cancelled'];return '<section class="clean-card"><div class="panel-head"><div><p class="tag">ORDER RECEIVING</p><h1>Orders</h1><p>Exact size quantities, subitems and custom design data are kept with each order.</p></div></div><div class="order-toolbar"><input id="orderSearch" value="'+esc(state.orderQuery)+'" placeholder="Search order, customer or phone"><div>'+['All',...statuses].map(s=>'<button data-order-filter="'+s+'" class="'+(state.orderFilter===s?'active':'')+'">'+s+'</button>').join('')+'</div></div><div class="portal-order-list">'+(list.length?list.map(o=>{const lines=orderLines(o.id);return '<article class="portal-order"><header><div><span>#'+esc(o.order_code)+'</span><h2>'+esc(o.customer_name||o.business||'Customer')+'</h2><small>'+esc(o.phone)+' · '+new Date(o.created_at).toLocaleString()+'</small></div><div><strong>'+money(o.total||0)+'</strong>'+(canOrderStatus()?'<select data-order-status="'+o.id+'">'+statuses.map(s=>'<option '+(o.status===s?'selected':'')+'>'+s+'</option>').join('')+'</select>':'<b>'+esc(o.status)+'</b>')+'</div></header><div class="portal-order-lines">'+lines.map(l=>'<div><span><b>'+esc(l.item_name)+'</b><small>'+esc(l.item_code||'')+' · '+esc([l.color,l.size].filter(Boolean).join(' · ')||l.item_type)+'</small></span><b>× '+l.qty+'</b><strong>'+money(Number(l.unit_price||0)*Number(l.qty||0))+'</strong>'+(l.design_json?'<details><summary>Design / roster</summary><pre>'+esc(JSON.stringify(l.design_json,null,2))+'</pre></details>':'')+'</div>').join('')+'</div><footer><span>'+esc(o.delivery||'')+'</span><span>'+esc(o.payment||'')+'</span><span>'+esc(o.address||'')+'</span></footer></article>';}).join(''):'<div class="empty-admin">No matching orders.</div>')+'</div></section>';}
  function customerOrderCount(id){return state.orders.filter(o=>o.customer_id===id).length;}
  function customerCart(id){return state.carts.find(c=>c.customer_id===id)||null;}
  function customersView(){
    const q=state.customerQuery.trim().toLowerCase(),list=state.customers.filter(c=>!q||[c.name,c.phone,c.business_name,c.job_title].join(' ').toLowerCase().includes(q));
    return '<section class="clean-card"><div class="panel-head"><div><p class="tag">CUSTOMER ACCOUNTS</p><h1>Customers</h1><p>Each verified phone number stays connected to one customer, profile and order history.</p></div><button class="ghost-btn" data-action="refresh-data">Refresh</button></div><div class="list-controls"><input id="customerSearch" type="search" value="'+esc(state.customerQuery)+'" placeholder="Search name, phone, business or role"><span>'+list.length+' customer'+(list.length===1?'':'s')+'</span></div><div class="customer-admin-list">'+(list.length?list.map(c=>{const cart=customerCart(c.id),orders=customerOrderCount(c.id);return '<article class="customer-admin-card"><div class="customer-avatar">'+esc((c.name||'?').slice(0,1).toUpperCase())+'</div><div class="customer-main"><b>'+esc(c.name||'Name not set')+'</b><span>'+esc(c.phone||'')+'</span><small>'+esc([c.job_title,c.business_name].filter(Boolean).join(' · ')||'No business details')+'</small></div><div class="customer-stats"><span><b>'+orders+'</b><small>orders</small></span><span><b>'+Number(cart?.piece_count||0)+'</b><small>cart pcs</small></span></div><div class="customer-time"><small>Last seen</small><b>'+new Date(c.last_seen_at||c.created_at).toLocaleString()+'</b><small>Joined '+new Date(c.created_at).toLocaleDateString()+'</small></div></article>';}).join(''):'<div class="empty-admin">No customers yet.</div>')+'</div></section>';
  }
  function cartItemSummary(item){const opts=[];(item.bulkLines||[]).forEach(l=>{if(Number(l.qty||0)>0)opts.push([l.color,l.size].filter(Boolean).join(' · ')+' × '+l.qty)});(item.subitems||[]).forEach(si=>(si.lines||[]).forEach(l=>{if(Number(l.qty||0)>0)opts.push((si.name||'Subitem')+' '+[l.color,l.size].filter(Boolean).join(' · ')+' × '+l.qty)}));if(item.sizeQuantities)Object.entries(item.sizeQuantities).forEach(([size,qty])=>{if(Number(qty)>0)opts.push(size+' × '+qty)});return '<div class="live-cart-item"><div><b>'+esc(item.name||'Item')+'</b><small>'+esc([item.code,item.detail].filter(Boolean).join(' · '))+'</small>'+(opts.length?'<em>'+opts.slice(0,10).map(esc).join(' / ')+'</em>':'')+'</div><span>× '+Number(item.qty||1)+'</span><strong>'+money(item.total||0)+'</strong></div>';}
  function cartsView(){
    const list=state.carts.filter(c=>Number(c.piece_count||0)>0);
    return '<section class="clean-card"><div class="panel-head"><div><p class="tag">LIVE CUSTOMER CARTS</p><h1>Who added what</h1><p>Shows the latest saved cart for each verified customer. Updates automatically while the portal is open.</p></div><button class="ghost-btn" data-action="refresh-data">Refresh now</button></div><div class="live-cart-list">'+(list.length?list.map(c=>'<article class="live-cart-card"><header><div><b>'+esc(c.customers?.name||'Customer')+'</b><span>'+esc(c.customers?.phone||'')+'</span><small>'+esc([c.customers?.job_title,c.customers?.business_name].filter(Boolean).join(' · '))+'</small></div><div><strong>'+Number(c.piece_count||0)+' pcs</strong><b>'+money(c.total||0)+'</b><small>'+new Date(c.updated_at).toLocaleString()+'</small></div></header><div class="live-cart-items">'+((c.items||[]).length?(c.items||[]).map(cartItemSummary).join(''):'<div class="empty-admin">Cart has no item details.</div>')+'</div></article>').join(''):'<div class="empty-admin">No verified customer has items in cart right now.</div>')+'</div></section>';
  }
  function activityView(){return '<section class="clean-card"><div class="panel-head"><div><p class="tag">VERIFIED CUSTOMER ACTIVITY</p><h1>Customer activity</h1><p>Login, cart, checkout, profile and order actions recorded after OTP verification.</p></div><button class="ghost-btn" data-action="refresh-data">Refresh</button></div><div class="activity-list">'+(state.activity.length?state.activity.map(a=>'<article><div><b>'+esc(a.event_type.replaceAll('_',' '))+'</b><small>'+new Date(a.created_at).toLocaleString()+'</small></div><span>'+esc(a.customers?.name||'')+'<small>'+esc(a.customers?.phone||'')+'</small></span><pre>'+esc(JSON.stringify(a.payload||{},null,2))+'</pre></article>').join(''):'<div class="empty-admin">No verified customer activity yet.</div>')+'</div></section>';}
  function accountsView(){return '<section class="clean-card"><div class="panel-head"><div><p class="tag">ACCESS CONTROL</p><h1>Staff & management accounts</h1><p>Create Admin, Management, Staff and Order Receiving logins.</p></div></div><form id="accountCreate" class="account-create"><label>Name<input name="name" required></label><label>Username<input name="username" required></label><label>Role<select name="role">'+roles.map(r=>'<option value="'+r+'">'+labels[r]+'</option>').join('')+'</select></label><label>Password<input type="password" name="password" minlength="8" required></label><button class="primary-btn">Create account</button></form><div class="account-list">'+state.profiles.map(p=>'<article><div><b>'+esc(p.name)+'</b><small>@'+esc(p.username)+'</small></div><select data-account-role="'+p.id+'">'+roles.map(r=>'<option value="'+r+'" '+(p.role===r?'selected':'')+'>'+labels[r]+'</option>').join('')+'</select><label class="account-active"><input type="checkbox" data-account-active="'+p.id+'" '+(p.active?'checked':'')+'> Active</label><input type="password" data-account-password="'+p.id+'" placeholder="New password optional"><button data-action="save-account" data-id="'+p.id+'">Save</button></article>').join('')+'</div></section>';}

  async function loadAll(silent=false){
    if(!silent)state.loading=true;state.error='';try{
      await B.hydrate();state.products=S.getProducts();
      const client=sb();
      const base=await Promise.all([client.from('categories').select('*').order('sort_order'),client.from('subcategories').select('*').order('sort_order'),B.listSubitems(),client.from('orders').select('*').order('created_at',{ascending:false}).limit(250),client.from('order_items').select('*').order('created_at',{ascending:true}).limit(1500)]);
      if(base[0].error)throw base[0].error;if(base[1].error)throw base[1].error;if(base[3].error)throw base[3].error;if(base[4].error)throw base[4].error;
      state.categories=base[0].data||[];state.subcategories=base[1].data||[];state.subitems=base[2]||[];state.orders=base[3].data||[];state.orderItems=base[4].data||[];
      if(requested==='admin'||requested==='management'){
        const [a,c,cart]=await Promise.all([client.from('customer_activity').select('*,customers(name,phone)').order('created_at',{ascending:false}).limit(500),client.from('customers').select('*').order('last_seen_at',{ascending:false}).limit(1000),client.from('customer_carts').select('*,customers(id,name,phone,business_name,job_title)').order('updated_at',{ascending:false}).limit(1000)]);
        if(!a.error)state.activity=a.data||[];if(!c.error)state.customers=c.data||[];if(!cart.error)state.carts=cart.data||[];
      }
      if(requested==='admin'){state.profiles=await B.listProfiles();}
    }catch(e){state.error=e.message||String(e);}finally{state.loading=false;render();}
  }
  function syncProductEditor(){if(!state.editor)return;root.querySelectorAll('[data-p]').forEach(el=>{let v=el.value;if(['price','mrp','stock'].includes(el.dataset.p))v=Number(v||0);state.editor[el.dataset.p]=v;});root.querySelectorAll('[data-v]').forEach(el=>{const i=Number(el.dataset.i);if(!state.editor.variants[i])return;let v=el.value;if(['stock','price'].includes(el.dataset.v))v=Number(v||0);state.editor.variants[i][el.dataset.v]=v;});state.editor.subItemIds=[...root.querySelectorAll('[data-sub-link]:checked')].map(x=>x.dataset.subLink);}
  function syncSubEditor(){if(!state.subEditor)return;root.querySelectorAll('[data-si]').forEach(el=>{let v=el.value;if(el.dataset.si==='price')v=Number(v||0);state.subEditor[el.dataset.si]=v;});root.querySelectorAll('[data-sv]').forEach(el=>{const i=Number(el.dataset.i);if(!state.subEditor.variants[i])return;let v=el.value;if(['stock','price'].includes(el.dataset.sv))v=Number(v||0);state.subEditor.variants[i][el.dataset.sv]=v;});}
  const validManualCode=v=>/^(?=.*[A-Z])(?=.*[0-9])[A-Z0-9]{6}$/.test(String(v||'').trim().toUpperCase());
  async function saveProduct(e){e.preventDefault();syncProductEditor();const p=state.editor;if(!p.name.trim()){notify('Product name is required.');return;}if(!p.categoryId){notify('Select a category.');return;}if(!String(p.barcode||'').trim()&&String(p.code||'').trim()&&!validManualCode(p.code)){notify('Manual item code must be 6 characters with letters and numbers.');return;}if(p.type==='Simple')p.variants=[];else if(!(p.variants||[]).length){notify('Add at least one size/option row.');return;}try{await B.upsertProduct(p);state.editor=null;await loadAll();notify('Product saved.');}catch(err){notify(err.message||'Could not save product');}}
  async function saveSubitem(e){e.preventDefault();syncSubEditor();if(!state.subEditor.name.trim()){notify('Subitem name is required.');return;}if(!String(state.subEditor.barcode||'').trim()&&String(state.subEditor.code||'').trim()&&!validManualCode(state.subEditor.code)){notify('Manual item code must be 6 characters with letters and numbers.');return;}try{await B.upsertSubitem(state.subEditor);state.subEditor=null;await loadAll();notify('Subitem saved.');}catch(err){notify(err.message||'Could not save subitem');}}
  async function uploadMany(files,folder){const out=[];for(const f of files)out.push(await B.uploadImage(f,folder));return out;}
  async function adjustStock(id,kind,delta){try{const client=sb();let r;if(kind==='product-variant')r=await client.rpc('adjust_stock',{p_variant:id,p_delta:delta,p_reason:'Portal stock adjustment'});else if(kind==='product')r=await client.rpc('adjust_product_stock',{p_product:id,p_delta:delta,p_reason:'Portal stock adjustment'});else r=await client.rpc('adjust_subitem_stock',{p_variant:id,p_delta:delta,p_reason:'Portal stock adjustment'});if(r.error)throw r.error;await loadAll();notify('Stock updated.');}catch(e){notify(e.message||'Stock update failed');}}

  function bind(){
    root.querySelector('#portalLogin')?.addEventListener('submit',async e=>{e.preventDefault();state.error='';const fd=new FormData(e.currentTarget);try{state.profile=await B.staffSignIn(fd.get('username'),fd.get('password'));if(!roleOkay()){render();return;}await loadAll();}catch(err){state.error=err.message||'Login failed';render();}});
    root.querySelectorAll('[data-view]').forEach(x=>x.addEventListener('click',()=>{state.view=x.dataset.view;state.menu=false;state.editor=null;state.subEditor=null;state.query='';render();}));
    root.querySelector('[data-action="menu"]')?.addEventListener('click',()=>{state.menu=!state.menu;render();});
    root.querySelectorAll('[data-action="logout"]').forEach(x=>x.addEventListener('click',async()=>{await B.staffSignOut();state.profile=null;render();}));
    root.querySelector('[data-action="open-store"]')?.addEventListener('click',()=>location.href='index.html');
    root.querySelectorAll('[data-action="refresh-data"]').forEach(x=>x.addEventListener('click',()=>loadAll(false)));
    root.querySelector('[data-action="new-product"]')?.addEventListener('click',()=>beginProduct(null));
    root.querySelectorAll('[data-action="edit-product"]').forEach(x=>x.addEventListener('click',()=>beginProduct(state.products.find(p=>p.id===x.dataset.id))));
    root.querySelector('[data-action="cancel-product"]')?.addEventListener('click',()=>{state.editor=null;render();});
    root.querySelectorAll('[data-edit-section]').forEach(x=>x.addEventListener('click',()=>{syncProductEditor();document.activeElement?.blur?.();state.editSections[x.dataset.editSection]=!state.editSections[x.dataset.editSection];render();}));
    root.querySelector('#productEditor')?.addEventListener('submit',saveProduct);
    root.querySelectorAll('[data-p]').forEach(x=>x.addEventListener('change',()=>{syncProductEditor();if(x.dataset.p==='categoryId'){state.editor.subcategoryId='';render();}}));
    root.querySelector('[data-action="add-variant"]')?.addEventListener('click',()=>{syncProductEditor();state.editor.variants.push({color:'',size:'',stock:0,price:Number(state.editor.price||0),barcode:'',image:'',active:true});render();});
    root.querySelectorAll('[data-remove-variant]').forEach(x=>x.addEventListener('click',()=>{syncProductEditor();state.editor.variants.splice(Number(x.dataset.removeVariant),1);render();}));
    root.querySelectorAll('[data-remove-product-image]').forEach(x=>x.addEventListener('click',()=>{syncProductEditor();state.editor.images.splice(Number(x.dataset.removeProductImage),1);render();}));
    root.querySelector('#productImages')?.addEventListener('change',async e=>{syncProductEditor();try{const urls=await uploadMany([...e.target.files],'products');state.editor.images.push(...urls);render();}catch(err){notify(err.message||'Upload failed');}});
    root.querySelector('[data-action="open-subitems"]')?.addEventListener('click',()=>{syncProductEditor();state.editor=null;state.view='subitems';render();});
    root.querySelectorAll('[data-action="delete-product"]').forEach(x=>x.addEventListener('click',async()=>{const p=state.products.find(v=>v.id===x.dataset.id);if(!p||!confirm('Delete '+p.name+'?'))return;try{await B.deleteProduct(p.id);await loadAll();notify('Product deleted.');}catch(e){notify(e.message||'Delete failed');}}));
    root.querySelector('#productSearch')?.addEventListener('input',e=>{state.query=e.target.value;render();requestAnimationFrame(()=>{const n=root.querySelector('#productSearch');n?.focus();if(n)try{n.setSelectionRange(n.value.length,n.value.length);}catch(_){}});});
    root.querySelector('#stockSearch')?.addEventListener('input',e=>{state.query=e.target.value;render();requestAnimationFrame(()=>root.querySelector('#stockSearch')?.focus());});
    root.querySelector('#customerSearch')?.addEventListener('input',e=>{state.customerQuery=e.target.value;render();requestAnimationFrame(()=>{const n=root.querySelector('#customerSearch');n?.focus();if(n)try{n.setSelectionRange(n.value.length,n.value.length);}catch(_){}});});
    root.querySelectorAll('[data-stock-change]').forEach(x=>x.addEventListener('click',()=>{const amount=Math.max(1,Number(root.querySelector('[data-stock-amount="'+x.dataset.stockChange+'"]')?.value||1));adjustStock(x.dataset.stockChange,x.dataset.kind,amount*Number(x.dataset.sign));}));

    root.querySelector('#categoryForm')?.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),file=fd.get('image'),old=state.categories.find(c=>c.id===state.categoryEditor);try{const image=file?.size?await B.uploadImage(file,'categories'):(old?.image_url||'');await B.upsertCategory({id:old?.id,name:String(fd.get('name')).trim(),sub:String(fd.get('subtitle')||'').trim(),image});state.categoryEditor=null;await loadAll();notify(old?'Category updated.':'Category added.');}catch(err){notify(err.message||'Could not save category');}});
    root.querySelectorAll('[data-action="edit-category"]').forEach(x=>x.addEventListener('click',()=>{state.categoryEditor=x.dataset.id;render();}));
    root.querySelector('[data-action="cancel-category-edit"]')?.addEventListener('click',()=>{state.categoryEditor=null;render();});
    root.querySelectorAll('[data-subcategory-form]').forEach(f=>f.addEventListener('submit',async e=>{e.preventDefault();const name=new FormData(f).get('name');try{const r=await sb().from('subcategories').insert({category_id:f.dataset.subcategoryForm,name:String(name).trim()});if(r.error)throw r.error;await loadAll();notify('Subcategory added.');}catch(err){notify(err.message||'Could not add subcategory');}}));
    root.querySelectorAll('[data-action="delete-category"]').forEach(x=>x.addEventListener('click',async()=>{if(!confirm('Delete this category? Products will remain but lose their category.'))return;const r=await sb().from('categories').delete().eq('id',x.dataset.id);if(r.error)notify(r.error.message);else{await loadAll();notify('Category deleted.');}}));
    root.querySelectorAll('[data-action="delete-subcategory"]').forEach(x=>x.addEventListener('click',async()=>{const r=await sb().from('subcategories').delete().eq('id',x.dataset.id);if(r.error)notify(r.error.message);else await loadAll();}));

    root.querySelector('[data-action="new-subitem"]')?.addEventListener('click',()=>{state.subEditor=blankSub();render();});
    root.querySelectorAll('[data-action="edit-subitem"]').forEach(x=>x.addEventListener('click',()=>{const raw=state.subitems.find(v=>v.id===x.dataset.id);state.subEditor={id:raw.id,name:raw.name,code:raw.code||'',barcode:raw.barcode||'',price:Number(raw.price||0),optionTitle:raw.option_title||'Size',images:raw.images||[],variants:(raw.variants||[]).map(v=>({id:v.id,color:v.color||'',size:v.size||'',stock:Number(v.stock||0),price:Number(v.price??raw.price??0),barcode:v.barcode||'',image:v.image_url||'',active:v.active!==false})),active:raw.active!==false};render();}));
    root.querySelector('[data-action="close-sub-editor"]')?.addEventListener('click',()=>{state.subEditor=null;render();});
    root.querySelector('#subitemEditor')?.addEventListener('submit',saveSubitem);
    root.querySelector('[data-action="add-sub-variant"]')?.addEventListener('click',()=>{syncSubEditor();state.subEditor.variants.push({color:'',size:'',stock:0,price:Number(state.subEditor.price||0),barcode:'',image:'',active:true});render();});
    root.querySelectorAll('[data-remove-sub-variant]').forEach(x=>x.addEventListener('click',()=>{syncSubEditor();if(state.subEditor.variants.length>1)state.subEditor.variants.splice(Number(x.dataset.removeSubVariant),1);else state.subEditor.variants=[{color:'',size:'',stock:0,price:Number(state.subEditor.price||0),barcode:'',image:'',active:true}];render();}));
    root.querySelectorAll('[data-remove-sub-image]').forEach(x=>x.addEventListener('click',()=>{syncSubEditor();state.subEditor.images.splice(Number(x.dataset.removeSubImage),1);render();}));
    root.querySelector('#subImages')?.addEventListener('change',async e=>{syncSubEditor();try{const urls=await uploadMany([...e.target.files],'subitems');state.subEditor.images.push(...urls);render();}catch(err){notify(err.message||'Upload failed');}});

    root.querySelector('#orderSearch')?.addEventListener('input',e=>{state.orderQuery=e.target.value;render();requestAnimationFrame(()=>root.querySelector('#orderSearch')?.focus());});
    root.querySelectorAll('[data-order-filter]').forEach(x=>x.addEventListener('click',()=>{state.orderFilter=x.dataset.orderFilter;render();}));
    root.querySelectorAll('[data-order-status]').forEach(x=>x.addEventListener('change',async()=>{const r=await sb().from('orders').update({status:x.value,updated_at:new Date().toISOString()}).eq('id',x.dataset.orderStatus);if(r.error)notify(r.error.message);else{await loadAll();notify('Order status updated.');}}));

    root.querySelector('#accountCreate')?.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);try{await B.adminCreateAccount(Object.fromEntries(fd.entries()));state.profiles=await B.listProfiles();render();notify('Account created.');}catch(err){notify(err.message||'Could not create account');}});
    root.querySelectorAll('[data-action="save-account"]').forEach(x=>x.addEventListener('click',async()=>{const id=x.dataset.id,role=root.querySelector('[data-account-role="'+id+'"]')?.value,active=root.querySelector('[data-account-active="'+id+'"]')?.checked,password=root.querySelector('[data-account-password="'+id+'"]')?.value||'';try{await B.adminUpdateAccount({id,role,active,...(password?{password}:{})});state.profiles=await B.listProfiles();render();notify('Account updated.');}catch(err){notify(err.message||'Could not update account');}}));
  }
  function render(){
    if(!B?.configured?.()){root.innerHTML=setupScreen();return;}
    if(state.loading&&!state.profile){root.innerHTML='<div class="admin-loading">Loading portal…</div>';return;}
    if(!state.profile){root.innerHTML=loginScreen();bind();return;}
    if(!roleOkay()){root.innerHTML=wrongPortal();bind();return;}
    if(state.loading){root.innerHTML='<div class="admin-loading">Loading live data…</div>';return;}
    root.innerHTML=shell();bind();renderToast();
  }
  async function init(){
    if(!B?.configured?.()){state.loading=false;render();return;}
    try{state.profile=await B.staffProfile();}catch(_){}
    state.loading=false;if(state.profile&&roleOkay())await loadAll();else render();
  }
  init();
  setInterval(()=>{if(state.profile&&roleOkay()&&!state.loading&&(requested==='admin'||requested==='management'))loadAll(true);},30000);
})();
